Add nice bash headers

diff --git a/bin/git-large-files b/bin/git-large-files
--- a/bin/git-large-files
+++ b/bin/git-large-files
@@ -1,4 +1,16 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
+# https://kvz.io/blog/bash-best-practices.html
+# Exit on error. Append "|| true" if you expect an error.
+set -o errexit
+# Exit on error inside any functions or subshells.
+set -o errtrace
+# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
+set -o nounset
+# Catch the error in case mysqldump fails (but gzip succeeds) in `mysqldump |gzip`
+set -o pipefail
+# Turn on traces, useful while debugging.
+# set -o xtrace
+
 # https://stackoverflow.com/a/42544963
 git rev-list --objects --all |
   git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' |
diff --git a/bin/git-review b/bin/git-review
--- a/bin/git-review
+++ b/bin/git-review
@@ -1,14 +1,25 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
+# https://kvz.io/blog/bash-best-practices.html
+# Exit on error. Append "|| true" if you expect an error.
+set -o errexit
+# Exit on error inside any functions or subshells.
+set -o errtrace
+# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
+set -o nounset
+# Catch the error in case mysqldump fails (but gzip succeeds) in `mysqldump |gzip`
+set -o pipefail
+# Turn on traces, useful while debugging.
+# set -o xtrace
 
 usage() {
-    echo "Usage: $0 [repository] branch"
+    echo "Usage: ${1##*/} [repository] branch"
 }
 
 if [[ $# -eq 0 ]]; then
-    usage
+    usage "$0"
     exit 1
 elif [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
-    usage
+    usage "$0"
     exit 0
 elif [[ $# -eq 1 ]]; then
     REPOSITORY="origin"
diff --git a/bin/grapper b/bin/grapper
--- a/bin/grapper
+++ b/bin/grapper
@@ -1,8 +1,15 @@
 #!/usr/bin/env sh
 # https://kvz.io/blog/bash-best-practices.html
+# Exit on error. Append "|| true" if you expect an error.
 set -o errexit
-set -o pipefail
+# Exit on error inside any functions or subshells.
+set -o errtrace
+# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
 set -o nounset
+# Catch the error in case mysqldump fails (but gzip succeeds) in `mysqldump |gzip`
+set -o pipefail
+# Turn on traces, useful while debugging.
+# set -o xtrace
 
 if [ "${1:-}" == "-h" ] || [ "${1:-}" == "--help" ]; then
     echo "Usage: $(basename $0) [version]"
